### ISSUE TITLE
[Client Step 11.1] missing isMine field in Message fragment 

### ISSUE THREAD

**Issue by milenazuccarelli** [Urigo/WhatsApp-Clone-Tutorial#17]
Hey!

In the tutorial, in chapter 11, Client step 11.1, there seems to be a missing instruction to add `isMine` inside of the Message fragment in `src/graphql/fragments/message.fragment.ts`. 

The change was made in [this commit](https://github.com/Urigo/WhatsApp-Clone-Client-React/commit/420318caa56b8cfab3f1871a483224a216a309da).

**Comment by Urigo** [comment]
Thank you @milenazuccarelli !

I've added it and added you to the contributors on the bottom of the README on the text repo

**Comment by milenazuccarelli** [comment]
Thanks @Urigo !
