### ISSUE TITLE
 Step 8: Sending messages -- Cannot read property 'chat' of undefined

### ISSUE THREAD

**Issue by braedongough** [Urigo/WhatsApp-Clone-Tutorial#18]
After having gone through all of the steps in section 8, I'm running into a problem where the app crashes when clicking on a chat returning with the error:  `Cannot read property 'chat' of undefined`. It appears to be stemming from ChatRoomScreen line 66, which doesn't make it any more clear. 

I finally gave up debugging it and cloned the git repo at the exact steps I had finished at and it appears I'm also receiving the error there as well. Are you able to reproduce on your end? 

I'm using [master-step8](https://github.com/Urigo/WhatsApp-Clone-Client-React/tree/master-step8) for the client and [master-step6](https://github.com/Urigo/WhatsApp-Clone-Server/tree/master-step6) which appear to align with the project at the end of [step 8](https://www.tortilla.academy/Urigo/WhatsApp-Clone-Tutorial/master/next/step/8)

![4739375ac05cbf17d0b93f8c570dd9dd](https://user-images.githubusercontent.com/38016720/62421816-2602f600-b6a8-11e9-99da-7c031b0e8dd1.gif)

**Comment by Urigo** [comment]
@braedongough I've just tried to reproduce it locally but couldn't...

Can you maybe share more information about the error?
Maybe the Javascript chat objects?

**Comment by braedongough** [comment]
Link to my chats db: (https://github.com/braedongough/whatsapp-clone/blob/master/whatsapp-clone-server/db.ts

Full repo: https://github.com/braedongough/whatsapp-clone

I can see the steps in the tutorial have been updated to use the latest version of apollo, although I'm hoping that it shouldn't have any impact on this issue, as it was posted before the update.

**Comment by braedongough** [comment]
I've just cloned client step8 and server step6 with the updates that have been added since and it's working on my machine now. Not sure what was wrong with the old code but no use in debugging it now. Thanks!

**Comment by Urigo** [comment]
awesome @braedongough and thanks for the feedback and update
