### ISSUE TITLE
[Client Step 1.2] Upgrade packages description should handle case when packages are already latest

### ISSUE THREAD

**Issue by jeriscc** [Urigo/WhatsApp-Clone-Tutorial#32]
I tried using `yarn add <package-name>` to install the latest version of each package. However, what it did was just add a `^` in front of each package version. Is the description of `yarn add <package-name>` inaccurate?

**Comment by Urigo** [comment]
@jeriscc there is also the second part of 1.2 that tells you to add `.npmrc` with `save-exact=true`

With both of those it should work.
Please reopen if it's not the case
