### ISSUE TITLE
[Client Step 1.3] Incorrect format command

### ISSUE THREAD

**Issue by jeriscc** [Urigo/WhatsApp-Clone-Tutorial#33]
In the docs, it says "Remember to run `yarn prettier` before you commit your changes!" That gave me a command-line error because no files were given nor specified. Perhaps, you should change the suggested command to `yarn format`?

**Comment by Poseid10ur** [comment]
Hi @Urigo 

I have created a PR [#48] for this.

**Comment by Urigo** [comment]
thank you @Poseid10ur will merge soon!

**Comment by Urigo** [comment]
thank you so much!
Fixed, deployed and added you as a co-author [here](https://github.com/Urigo/WhatsApp-Clone-Tutorial/commit/4d82232ba5e558cd5fac8392a398074a42186dae)
