### ISSUE TITLE
[Client Step 10.3] Issue with cache service

### ISSUE THREAD

**Issue by heisenbergCodes** [Urigo/WhatsApp-Clone-Tutorial#39]
I am getting the following error while running the client application.

This expression is not callable.
  Each member of the union type '(<T = any, TVariables = OperationVariables>(options: Fragment<TVariables>, optimistic?: boolean | undefined) => T | null) | (<FragmentType, TVariables = any>(options: Fragment<TVariables>, optimistic?: boolean | undefined) => FragmentType | null)' has signatures, but none of those signatures are compatible with each other.  TS2349

    50 |   }
    51 |   try {
  > 52 |     fullChat = client.readFragment<FullChat>({
       |                       ^
    53 |       id: chatIdFromStore,
    54 |       fragment: fragments.fullChat,
    55 |       fragmentName: 'FullChat',

**Comment by I3r41n** [comment]
Did you got to understand what was wrong? I'm facing the same issue

**Comment by heisenbergCodes** [comment]
Nothing so far.

**Comment by Fl4zher** [comment]
Anything new? Got the same issue...

**Comment by gpdeedler** [comment]
I'm experiencing the same issue as well...

**Comment by Urigo** [comment]
Fixed in the new version (will push later today).

You can change type Client on the top of the file to:
```
type Client = Pick<
  DataProxy,
  'readFragment' | 'writeFragment' | 'readQuery' | 'writeQuery'
>;
```

**Comment by Urigo** [comment]
also you should probably on the same step add the query typings from codegen:

```
import {
  MessageFragment,
  useMessageAddedSubscription,
  ChatsQuery,
} from '../graphql/types';
```
and
```
    data = client.readQuery<ChatsQuery>({
      query: queries.chats,
    });
```

and also check undefined on message.chat.id:
```
  const chatIndex = chats.findIndex((c: any) => {
    if (message === null || message.chat === null) return -1;
    return c.id === message?.chat?.id;
  });
```
