### ISSUE TITLE
[Client Step 7.3]

### ISSUE THREAD

**Issue by mpaus** [Urigo/WhatsApp-Clone-Tutorial#41]
There seems to be a problem with running this code. It happens in the index.tsx script located in the ChatRoomScreen folder on line 59 where you try to extract the chat object from the data object returned by the useQuery hook. The error that appears is "cannot read property chat of undefined". Seems to me that at the moment of extracting the chat object apollo is still loading the results, therefore data is still empty. Could you please take a look into it or tell me if I'm doing or if I understood something wrong.

Thanks

**Comment by Urigo** [comment]
thank you, you are right @mpaus 

I've fixed it in the new version and will push later today.

For now, the fix is instead of the old query, use:

```
  const { data } = useQuery<any>(getChatQuery, {
    variables: { chatId },
  });
  const chat = data?.chat;
```
