### ISSUE TITLE
[Client Step 13.2] 404 not found on step: update auth service to call signIn mutation

### ISSUE THREAD

**Issue by reymon359** [Urigo/WhatsApp-Clone-Tutorial#61]
When the commit code is referenced in the Client Step 13.2 there is a 

```
404: Not Found
```

![image](https://user-images.githubusercontent.com/31936665/82139487-6216da00-9828-11ea-91b2-b3bcfbac6c42.png)

![image](https://user-images.githubusercontent.com/31936665/82139489-64793400-9828-11ea-88b7-02e4758fa8f8.png)

**Comment by reymon359** [comment]
I have noticed that the file extension on the template is `.ts` instead of `.tsx`. Could it be that the problem? In that case, I would gladly submit a pull request to fix it :) https://github.com/Urigo/WhatsApp-Clone-Tutorial/blob/16602138247c3d9a2b071bd155b8df9ba0585371/.tortilla/manuals/templates/step13.tmpl#L74

**Comment by Urigo** [comment]
Good catch!

I've updated both the docs and renamed the file in the repo to `ts`.

Added you as a co-author as well!
