### ISSUE TITLE
Step 14 Problem displaying Bash code in Markdown

### ISSUE THREAD

**Issue by reymon359** [Urigo/WhatsApp-Clone-Tutorial#63]
The Markdown Bash code block in [this section](https://github.com/Urigo/WhatsApp-Clone-Tutorial/blob/16602138247c3d9a2b071bd155b8df9ba0585371/.tortilla/manuals/templates/step14.tmpl#L218) is not displaying properly 
![image](https://user-images.githubusercontent.com/31936665/82408985-0b4e1200-9a6d-11ea-8294-4d2f147f9dbd.png)

I think it is a problem related to the way the Markdown is rendered by Tortilla because GitHub renders the same code properly.
```bash
Welcome to psql 7.4.16, the PostgreSQL interactive terminal.

Type:  \\copyright for distribution terms
       \\h for help with SQL commands
       \\? for help on internal slash commands
       \\g or terminate with semicolon to execute query
       \\q to quit

template1
```

**Comment by Urigo** [comment]
Sorry about that, I've already updated it but haven't deployed a new version of the site.
It should be up in a couple of minutes, thanks for noticing!
