### ISSUE TITLE
Step 15 Advanced Rest Client is deprecated

### ISSUE THREAD

**Issue by reymon359** [Urigo/WhatsApp-Clone-Tutorial#67]
In step 15 it is recommended to use the Chrome extension Advanced Rest Client to retrieve the Unsplash API response. The problem is that this tool is deprecated and warned both, on the [Chrome Store](https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo) page and on its [GitHub repository](https://github.com/jarrodek/ChromeRestClient).

![image](https://user-images.githubusercontent.com/31936665/82414211-fd04f380-9a76-11ea-8703-f0c656872e25.png)

I suggest correcting it by referring to the [Desktop version](https://install.advancedrestclient.com/install) or another tool like [Postman](https://www.postman.com/).

**Comment by reymon359** [comment]
I submitted a pull request #68 trying to solve the issue.

**Comment by Urigo** [comment]
thank you for the fix!  merged and deployed!
