### ISSUE TITLE
Step 16 Server step 13.28 not found

### ISSUE THREAD

**Issue by reymon359** [Urigo/WhatsApp-Clone-Tutorial#73]
The server step referenced [here](https://github.com/Urigo/WhatsApp-Clone-Tutorial/blob/9bccba5e18696e3cdb10234e2b09472cd0a57ae0/.tortilla/manuals/templates/step16.tmpl#L347) is giving a `NOT FOUND!` message. 

![image](https://user-images.githubusercontent.com/31936665/82483016-fa86b600-9ad7-11ea-8b1a-d71dd2ef14d5.png)

I did not submit a PR to remove it because I thought that maybe the problem is that the reference to the files is missing or a similar issue.

**Comment by Urigo** [comment]
Fixed.  It referenced a bunch of wrong order commits throughout al the end of the tutorial.

Now it should make much more sense to follow....
