### ISSUE TITLE
Step 17 Client Step 15.10 not displaying the files

### ISSUE THREAD

**Issue by reymon359** [Urigo/WhatsApp-Clone-Tutorial#74]
The Client step 15.10 is not displaying the files changed.

![image](https://user-images.githubusercontent.com/31936665/82487596-ded2de00-9ade-11ea-8f6f-9984fb7b547e.png)

I checked[ the code](https://github.com/Urigo/WhatsApp-Clone-Tutorial/blob/9bccba5e18696e3cdb10234e2b09472cd0a57ae0/.tortilla/manuals/templates/step17.tmpl#L461) but I did not find anything wrong with it.

**Comment by Urigo** [comment]
Fixed.
It was pointing to the wrong commit and so were a bunch of other step references.
I fixed those and I hope now it would make more sense
